version: "3.9"
services:

  ### Prefect Database
  database:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orion
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data
    profiles: ["orion"]
  
  ### MinIO for flow storage
  minio:
    image: minio/minio:latest
    entrypoint: ["minio", "server", "--address", "0.0.0.0:9000", "--console-address", "0.0.0.0:9001", "/data"]
    volumes:
      - "minio:/data"
    ports:
      - 9000:9000
      - 9001:9001
    profiles: ["minio"]

  ### Prefect Orion API
  orion:
    image: prefecthq/prefect:2.7.1-python3.11
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["prefect", "orion", "start"]
    environment:
      - PREFECT_ORION_API_HOST=0.0.0.0
      - PREFECT_API_URL=http://orion:4200/api
      - PREFECT_ORION_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/orion
    ports:
      - 4200:4200
    depends_on:
      - database
    profiles: ["orion"]

  ## Prefect Agent pipeline 1
  ## These services need to be adjusted according to a dockerfile and image with correct builds i.e. Yolov5
  agent1:
    image: custom-worker-image
    build:
      context: .
      dockerfile: pipeline.Dockerfile
    restart: always
    entrypoint: ["prefect", "agent", "start", "-q", "integer-pipeline"]
    environment:
      - PREFECT_API_URL=http://orion:4200/api
    profiles: ["agent"]

  ## Prefect Agent pipeline 2
  agent2:
    image: custom-worker-image
    build:
      context: .
      dockerfile: pipeline.Dockerfile
    restart: always
    entrypoint: ["prefect", "agent", "start", "-q", "string-pipeline"]
    environment:
      - PREFECT_API_URL=http://orion:4200/api
    profiles: ["agent"]
    
  ### Prefect CLI
  cli:
    image: prefecthq/prefect:2.7.1-python3.11
    entrypoint: "bash"
    working_dir: "/root/"
    volumes:
      - "./:/root/"
    environment:
      - PREFECT_API_URL=http://orion:4200/api
    profiles: ["cli"]
      
volumes:
  prefect:
  db:
  minio:
networks:
  default:
    name: prefect-network